# Generated by Django 4.2.5 on 2023-11-06 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poro',
            fields=[
                ('hash_key', models.TextField(auto_created=60)),
                ('UUID', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='poro', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
