# Generated by Django 4.2.5 on 2023-11-08 00:52

from django.db import migrations, models
import poro.models


class Migration(migrations.Migration):

    dependencies = [
        ('poro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poro',
            name='hash_key',
            field=models.TextField(auto_created=poro.models.get_random_hash),
        ),
    ]
